In [6]:
import numpy as np

Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be
   array
  
             [ 0.,  1.,  0.],         
             [ 0.,  0.,  1.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
            [ 1.,  0.,  0.]
            
            

In [25]:
# ar=np.array(list(map(int, input('Enter space separated list values: ').split())))
ar=[2, 3, 2, 2, 2, 1]
arr=np.array(ar)
uniqueValues=np.unique(ar)
uniqueValues.sort()
valueMap={}
count=0
for i in uniqueValues:
  valueMap[i]=count
  count+=1
result=np.zeros((len(ar), len(uniqueValues)))
for i in range(len(arr)):
  result[i, valueMap[arr[i]]]=1
print(result)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


Drop all missing values from an array Input: np.array(`[1,2,3,np.nan,5,6,7,np.nan]`) Desired Output: array(`[ 1.,2.,3.,5.,6.,7.]`)

In [52]:
def get():
  stringWaliValues=list(input('Enter space separated values: ').split(','))
  intWaliValues=[0 for i in stringWaliValues]
  for index, value in enumerate(stringWaliValues):
    if value != ' ':
      intWaliValues[index]=int(value)
    else:
      intWaliValues[index]=np.nan
  return intWaliValues
arr=np.array(get())
print(arr[~np.isnan(arr)])

Enter space separated values: 1, ,3, ,4, ,5
[1. 3. 4. 5.]


Find Index of Local maxima from an array. Input: a = np.array(`[1, 3, 7, 1, 2, 6, 0, 1]`) Desired Output: array(`[2, 5]`)

In [57]:
ar=list(map(int, input('Enter space separated values: ').split()))
result=[]
for i in range(1, len(ar)):
  if ar[i]-ar[i-1]<0:#if grad < 0
    result.append(i-1)
print(result)


Enter space separated values: 1 2
[]


From the given 1d array arr, generate a 2d matrix using strides,
For example for an array (`[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]`)with a window length of w=4 and strides of s=2, like `[[0,1,2,3], [2,3,4,5], [4,5,6,7]..]`
w and s will be provided by user
Calculate the moving average.

In [3]:
# ar=list(map(int, input('Enter space separated values: ').split()))
ar=[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
w=int(input('Enter window size: '))
s=int(input('Enter stride size: '))
b=float(input('Enter weight of cur average for moving average: '))
resultZeros=[]
resultMirror=[]
resultRollback=[]
temp=[]
averages=([], [], [])
for i in range(0, len(ar), s):
  temp=ar[i:i+w]
  if i+w>=len(ar):
    zeros=ar[i:i+w]
    mirror=ar[i:i+w]
    rollback=ar[i:i+w]

    zeros+=[0]*(w-len(temp))
    mirror+=mirror[::-1]
    mirror=mirror[0:w]
    rollback=rollback+ar[0:w-len(temp)]

    resultZeros.append(zeros)
    resultMirror.append(mirror)
    resultRollback.append(rollback)
    break
  resultZeros.append(temp)
  resultMirror.append(temp)
  resultRollback.append(temp)
print(f'2d matrix in case of zeros: {resultZeros}\n2d matrix in case of mirror: {resultMirror}\n2d matrix in case of rollback: {resultRollback}')
for zero, mirror, rollback in zip(resultZeros, resultMirror, resultRollback):
  averages[0].append(sum(zero)/w)
  averages[1].append(sum(mirror)/w)
  averages[2].append(sum(rollback)/w)
print(f'Averages in case of zeros: {averages[0]}\nAverages in case of mirror: {averages[1]}\nAverages in case of rollback: {averages[2]}')
for i in range(1, len(averages[0])):
  print(f'Moving average at {i} (zeros): {(b*averages[0][i]+(1-b)*averages[0][i-1])}')
  print(f'Moving average at {i} (mirror): {(b*averages[1][i]+(1-b)*averages[1][i-1])}')
  print(f'Moving average at {i} (rollback): {(b*averages[2][i]+(1-b)*averages[2][i-1])}')


2d matrix in case of zeros: [[0, 1, 2, 3], [2, 3, 4, 5], [4, 5, 6, 7], [6, 7, 8, 9], [8, 9, 10, 11], [10, 11, 12, 13], [12, 13, 14, 0]]
2d matrix in case of mirror: [[0, 1, 2, 3], [2, 3, 4, 5], [4, 5, 6, 7], [6, 7, 8, 9], [8, 9, 10, 11], [10, 11, 12, 13], [12, 13, 14, 14]]
2d matrix in case of rollback: [[0, 1, 2, 3], [2, 3, 4, 5], [4, 5, 6, 7], [6, 7, 8, 9], [8, 9, 10, 11], [10, 11, 12, 13], [12, 13, 14, 0]]
Averages in case of zeros: [1.5, 3.5, 5.5, 7.5, 9.5, 11.5, 9.75]
Averages in case of mirror: [1.5, 3.5, 5.5, 7.5, 9.5, 11.5, 13.25]
Averages in case of rollback: [1.5, 3.5, 5.5, 7.5, 9.5, 11.5, 9.75]
Moving average at 1 (zeros): 2.3
Moving average at 1 (mirror): 2.3
Moving average at 1 (rollback): 2.3
Moving average at 2 (zeros): 4.300000000000001
Moving average at 2 (mirror): 4.300000000000001
Moving average at 2 (rollback): 4.300000000000001
Moving average at 3 (zeros): 6.3
Moving average at 3 (mirror): 6.3
Moving average at 3 (rollback): 6.3
Moving average at 4 (zeros): 8.3
Mov