In [2]:
import numpy as np

### 1. Create a function to check whether a numpy array has zero values or not?

In [3]:
a=np.array([1,2,3,4,0,5,6,6])
b=np.where(a==0)
c= f'Zeroes present at {b[0]}'if b[0] else 'No zeroes present'
print(c)

Zeroes present at [4]


### 2.Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [4]:
a=np.arange(10, 80, 5)
# a=np.array([12,2,4,4,45])
passing=28
passingStudents=a[a>passing]
passingStudentsMean=np.mean(passingStudents)
passingStudentsMedian=np.median(passingStudents)
print(f'The mean of marks of passing students is:{passingStudentsMean}\nThe median marks of passing students are:{passingStudentsMedian}')

The mean of marks of passing students is:52.5
The median marks of passing students are:52.5


### 3.Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [5]:
dateOfBirth=np.array([np.datetime64('2000-02-01'), np.datetime64('2002-09-23'), np.datetime64('2004-08-07')])
def calcAge(x):
    # return np.subtract(np.datetime64('now'),x)//np.timedelta64(365, 'D')
    return (np.datetime64('today')-x)//np.timedelta64(365,'D')
ages=calcAge(dateOfBirth)
# print(ages)
def labelAge(x):
    if x>21:
        return 'Fourth'
    elif x>20:
        return 'Third'
    elif x>19:
        return 'Second'
    elif x>18:
        return 'First'
    else:
        return "INVALID"
print(np.vectorize(labelAge)(ages))


['Fourth' 'Fourth' 'Second']


### 4.Create a function to sort 2d Array by a column.

In [6]:
n=5
arr = np.random.randint(10, 100, size=(n, n))
print(arr)
print('\n\n')
ar=np.sort(arr, axis=0)
print("Sorted:")
print(ar)

[[96 97 83 30 66]
 [44 15 74 93 28]
 [74 15 38 36 42]
 [64 50 71 74 68]
 [41 73 57 10 88]]



Sorted:
[[41 15 38 10 28]
 [44 15 57 30 42]
 [64 50 71 36 66]
 [74 73 74 74 68]
 [96 97 83 93 88]]
